name: pavans_drm_video_player_android
description: Android implementation of the video_player plugin.
repository: https://github.com/parthkalariyadev/video_player_test/tree/main/video_player/video_player_android
issue_tracker: https://github.com/parthkalariyadev/video_player_test/issues
version: 2.3.6

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: pavans_drm_video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  pavans_drm_video_player_platform_interface:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/pavans_drm_video_player_platform_interface
      ref: b8cf607744e64aaf242bfdd091a51108e417f42a

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^2.0.1
