name: video_player_example
description: Demonstrates how to use the video_player plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  video_player:
    # When depending on this package from a real application you should use:
    #   video_player: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dependency_overrides:
  video_player:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player
      ref: fb940c2061cc5173908145a6996c2e1602cb6835
  video_player_platform_interface:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_platform_interface
      ref: fb940c2061cc5173908145a6996c2e1602cb6835
  video_player_android:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_android
      ref: fb940c2061cc5173908145a6996c2e1602cb6835
  video_player_web:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_web
      ref: fb940c2061cc5173908145a6996c2e1602cb6835
  video_player_avfoundation:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_avfoundation
      ref: fb940c2061cc5173908145a6996c2e1602cb6835

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path_provider: ^2.0.6
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
    - assets/Butterfly-209.mp4
    - assets/Butterfly-209.webm
    - assets/bumble_bee_captions.srt
    - assets/bumble_bee_captions.vtt
    - assets/Audio.mp3
