name: pavans_drm_video_player
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/parthkalariyadev/video_player_test/tree/main/video_player/video_player
issue_tracker: https://github.com/parthkalariyadev/video_player_test/issues
version: 2.4.4

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: pavans_drm_video_player_android
      ios:
        default_package: video_player_avfoundation
      web:
        default_package: video_player_web

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  #video_player_android: ^2.3.5
  video_player_avfoundation: ^2.2.17
  #video_player_platform_interface: ^5.1.1
  video_player_web: ^2.0.0
  pointycastle: ^3.6.2
  convert: ^3.1.0
  pavans_drm_video_player_platform_interface:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/pavans_drm_video_player_platform_interface
      ref: b8cf607744e64aaf242bfdd091a51108e417f42a
  pavans_drm_video_player_android:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/pavans_drm_video_player_android
      ref: 6785d3a6c2cfc686db24714b8e51c87da0893969

dependency_overrides:
  video_player_web:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_web
      ref: fb940c2061cc5173908145a6996c2e1602cb6835

  video_player_avfoundation:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_avfoundation
      ref: fb940c2061cc5173908145a6996c2e1602cb6835

dev_dependencies:
  flutter_test:
    sdk: flutter
