name: drm_video_player_android
description: Android implementation of the video_player plugin.
repository: https://github.com/parthkalariyadev/video_player_test/tree/main/video_player/video_player_android
issue_tracker: https://github.com/parthkalariyadev/video_player_test/issues
version: 2.3.6

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: drm_video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter

  # use this for local path.
  # drm_video_player_platform_interface:
    # path: ../video_player_platform_interface

  # use this for github path.
  drm_video_player_platform_interface:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_platform_interface
      ref: 026745b11281320bc97be020dc0f38f7d99ba849

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^2.0.1
