name: video_player_android
description: Android implementation of the video_player plugin.
repository: https://github.com/parthkalariyadev/video_player_test/tree/main/video_player/video_player_android
issue_tracker: https://github.com/parthkalariyadev/video_player_test/issues
version: 2.3.6

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      android:
        dartPluginClass: AndroidVideoPlayer
        package: io.flutter.plugins.videoplayer
        pluginClass: VideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ^5.1.1

dependency_overrides:
  video_player_platform_interface:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_platform_interface
      ref: 7907187b466e2c085c4ef2cac493999f09f51035

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^2.0.1
