package io.flutter.plugins

import androidx.annotation.Keep
import dev.flutter.plugins.integration_test.IntegrationTestPlugin
import io.flutter.Log
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry
import io.flutter.plugins.pathprovider.PathProviderPlugin
import io.flutter.plugins.videoplayer.VideoPlayerPlugin

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
object GeneratedPluginRegistrant {
    private const val TAG = "GeneratedPluginRegistrant"
    fun registerWith(flutterEngine: FlutterEngine) {
        val shimPluginRegistry = ShimPluginRegistry(flutterEngine)
        try {
            flutterEngine.plugins.add(IntegrationTestPlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin integration_test, dev.flutter.plugins.integration_test.IntegrationTestPlugin",
                e
            )
        }
        try {
            flutterEngine.plugins.add(PathProviderPlugin())
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin path_provider_android, io.flutter.plugins.pathprovider.PathProviderPlugin",
                e
            )
        }
        try {
            VideoPlayerPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.videoplayer.VideoPlayerPlugin"))
        } catch (e: Exception) {
            Log.e(
                TAG,
                "Error registering plugin video_player_android, io.flutter.plugins.videoplayer.VideoPlayerPlugin",
                e
            )
        }
    }
}