name: video_player_avfoundation
description: iOS implementation of the video_player plugin.
repository: https://github.com/parthkalariyadev/video_player_test/tree/main/video_player/video_player_avfoundation
issue_tracker: https://github.com/parthkalariyadev/video_player_test/issues
version: 2.3.5

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      ios:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FLTVideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: ">=4.2.0 <6.0.0"

dependency_overrides:
  video_player_platform_interface:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_platform_interface
      ref: 01f27a0d584296762ebb8cb7a4298ee36ec3601f

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^2.0.1
