name: drm_video_player_avfoundation
description: iOS implementation of the video_player plugin.
repository: https://github.com/parthkalariyadev/video_player_test/tree/main/video_player/video_player_avfoundation
issue_tracker: https://github.com/parthkalariyadev/video_player_test/issues
version: 2.3.5

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: drm_video_player
    platforms:
      ios:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FLTVideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  # use this for local path.
  # video_player_platform_interface:
    # path: ../video_player_platform_interface

  # use this for github path.
  video_player_platform_interface:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_platform_interface
      ref: 6726f8c00c3f03b760f512dcbdf696fd95094ef0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^2.0.1
