name: drm_video_player_web
description: Web platform implementation of video_player.
repository: https://github.com/parthkalariyadev/video_player_test/tree/main/video_player/video_player_web
issue_tracker: https://github.com/parthkalariyadev/video_player_test/issues
version: 2.0.10

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: drm_video_player
    platforms:
      web:
        pluginClass: VideoPlayerPlugin
        fileName: video_player_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # use this for local path.
  # drm_video_player_platform_interface:
    # path: ../video_player_platform_interface

  # use this for github path.
  drm_video_player_platform_interface:
    git:
      url: https://github.com/parthkalariyadev/video_player_test.git
      path: video_player/video_player_platform_interface
      ref: 026745b11281320bc97be020dc0f38f7d99ba849

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
